"""add unique constraints to email and telephone

Revision ID: 98e731c0baa5
Revises: e7c29344ad45
Create Date: 2026-01-08 19:02:42.464017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e731c0baa5'
down_revision: Union[str, Sequence[str], None] = 'e7c29344ad45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.drop_index(op.f('ix_utilisateur_telephone'), table_name='utilisateur')
    op.create_index(op.f('ix_utilisateur_telephone'), 'utilisateur', ['telephone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_telephone'), table_name='utilisateur')
    op.create_index(op.f('ix_utilisateur_telephone'), 'utilisateur', ['telephone'], unique=False)
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=False)
    # ### end Alembic commands ###
