"""Add verification_token_expires field to utilisateur

Revision ID: e7c29344ad45
Revises: 
Create Date: 2026-01-01 16:03:19.984845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c29344ad45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('utilisateur')]
    if 'verification_token_expires' not in columns:
        op.add_column('utilisateur', sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'verification_token_expires')
    # ### end Alembic commands ###
